apiVersion: v1
kind: RoleBinding
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::992382745816:user/github-ci
      username: github-ci
      groups:
        - system:masters