apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deplopment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 992382745816.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:00ee6d67545b081950fa65938da9f171abb3d693
        ports:
        - containerPort: 8080